2021-03-13 13:12:14,936 | DEBUG | proactor_events.py:623| Using proactor: IocpProactor
2021-03-13 13:13:37,955 | DEBUG | proactor_events.py:623| Using proactor: IocpProactor
2021-03-13 13:13:38,113 | DEBUG | proactor_events.py:623| Using proactor: IocpProactor
2021-03-13 13:16:09,660 | DEBUG | proactor_events.py:623| Using proactor: IocpProactor
2021-03-13 13:16:09,797 | DEBUG | proactor_events.py:623| Using proactor: IocpProactor
2021-03-13 13:18:08,712 | DEBUG | proactor_events.py:623| Using proactor: IocpProactor
2021-03-13 13:18:08,932 | DEBUG | proactor_events.py:623| Using proactor: IocpProactor
2021-03-13 13:18:18,265 | ERROR | log.py:224| Internal Server Error: /vacation
Traceback (most recent call last):
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\workbench3\learning\django\src\python-bootcamp\web_project\web_app\views.py", line 164, in vacation
    return render(request, 'vacation.html', context)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'endblock'. Did you forget to register or load this tag?
2021-03-13 13:18:18,265 | ERROR | log.py:224| Internal Server Error: /vacation
Traceback (most recent call last):
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\workbench3\learning\django\src\python-bootcamp\web_project\web_app\views.py", line 164, in vacation
    return render(request, 'vacation.html', context)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'endblock'. Did you forget to register or load this tag?
2021-03-13 13:18:18,295 | ERROR | basehttp.py:157| "GET /vacation HTTP/1.1" 500 125801
2021-03-13 13:18:18,295 | ERROR | basehttp.py:157| "GET /vacation HTTP/1.1" 500 125801
2021-03-13 13:18:46,171 | DEBUG | proactor_events.py:623| Using proactor: IocpProactor
2021-03-13 13:18:46,307 | DEBUG | proactor_events.py:623| Using proactor: IocpProactor
2021-03-13 13:18:52,558 | ERROR | log.py:224| Internal Server Error: /vacation
Traceback (most recent call last):
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\workbench3\learning\django\src\python-bootcamp\web_project\web_app\views.py", line 164, in vacation
    return render(request, 'vacation.html', context)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'endblock'. Did you forget to register or load this tag?
2021-03-13 13:18:52,558 | ERROR | log.py:224| Internal Server Error: /vacation
Traceback (most recent call last):
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\workbench3\learning\django\src\python-bootcamp\web_project\web_app\views.py", line 164, in vacation
    return render(request, 'vacation.html', context)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\workbench3\learning\django\venv\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'endblock'. Did you forget to register or load this tag?
2021-03-13 13:18:52,572 | ERROR | basehttp.py:157| "GET /vacation HTTP/1.1" 500 125801
2021-03-13 13:18:52,572 | ERROR | basehttp.py:157| "GET /vacation HTTP/1.1" 500 125801
